# Generated by Django 2.2.10 on 2020-06-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(default='', max_length=128)),
                ('label_mark', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='learntweet',
            name='tag',
        ),
    ]
