# Generated by Django 2.2.10 on 2020-06-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0002_auto_20200617_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntweet',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='tweesor.Label'),
        ),
    ]
