# Generated by Django 2.2.10 on 2020-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0003_learntweet_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydata',
            name='temp_location',
            field=models.TextField(default=''),
        ),
    ]
