# Generated by Django 2.2.10 on 2020-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0004_temporarydata_temp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydata',
            name='temp_created_at',
            field=models.TextField(default=''),
        ),
    ]
