# Generated by Django 2.2.10 on 2020-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0006_temporarydata_search_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntweet',
            name='created_at',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='learntweet',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='learntweet',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='learntweet',
            name='text_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='learntweet',
            name='tweet_id',
            field=models.IntegerField(default=''),
        ),
    ]
