# Generated by Django 2.2.10 on 2021-02-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweesor', '0009_auto_20201212_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='learntweet',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
